from datetime import datetime,timezone
from typing import Any
from sqlalchemy import String,Integer,Float,Boolean,DateTime,Text,ForeignKey,Index,JSON
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def utcnow(): return datetime.now(timezone.utc)
class World(Base):
 __tablename__="worlds"; id:Mapped[str]=mapped_column(String(64),primary_key=True); name:Mapped[str]=mapped_column(String(200)); world_type:Mapped[str]=mapped_column(String(80)); description:Mapped[str]=mapped_column(Text,default=""); current_timestamp:Mapped[int]=mapped_column(Integer,default=0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow)
class Entity(Base):
 __tablename__="entities"; id:Mapped[str]=mapped_column(String(80),primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); entity_type:Mapped[str]=mapped_column(String(50),index=True); name:Mapped[str]=mapped_column(String(200)); x:Mapped[float]=mapped_column(Float); y:Mapped[float]=mapped_column(Float); state_json:Mapped[dict[str,Any]]=mapped_column(JSON); attributes_json:Mapped[dict[str,Any]]=mapped_column(JSON); relationships_json:Mapped[list[str]]=mapped_column(JSON); source:Mapped[str]=mapped_column(String(100),default="seed"); freshness_status:Mapped[str]=mapped_column(String(30),default="fresh"); confidence:Mapped[float]=mapped_column(Float,default=1.0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow)
class Relationship(Base):
 __tablename__="relationships"; id:Mapped[int]=mapped_column(Integer,primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); source_entity_id:Mapped[str]=mapped_column(ForeignKey("entities.id")); target_entity_id:Mapped[str]=mapped_column(ForeignKey("entities.id")); relationship_type:Mapped[str]=mapped_column(String(80)); attributes_json:Mapped[dict[str,Any]]=mapped_column(JSON)
class Scenario(Base):
 __tablename__="scenarios"; id:Mapped[str]=mapped_column(String(80),primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); original_text:Mapped[str]=mapped_column(Text); action:Mapped[str]=mapped_column(String(100)); parameters_json:Mapped[list[dict[str,Any]]]=mapped_column(JSON); assumptions_json:Mapped[list[str]]=mapped_column(JSON); ambiguities_json:Mapped[list[str]]=mapped_column(JSON); valid:Mapped[bool]=mapped_column(Boolean); parser_name:Mapped[str]=mapped_column(String(100)); parser_version:Mapped[str]=mapped_column(String(30)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class SimulationBranch(Base):
 __tablename__="simulation_branches"; id:Mapped[str]=mapped_column(String(80),primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); parent_branch_id:Mapped[str|None]=mapped_column(ForeignKey("simulation_branches.id")); scenario_id:Mapped[str|None]=mapped_column(ForeignKey("scenarios.id"),index=True); branch_type:Mapped[str]=mapped_column(String(30)); name:Mapped[str]=mapped_column(String(200)); seed:Mapped[int]=mapped_column(Integer); duration_minutes:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30)); initial_state_hash:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class SimulationState(Base):
 __tablename__="simulation_states"; id:Mapped[int]=mapped_column(Integer,primary_key=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); timestamp:Mapped[int]=mapped_column(Integer,index=True); state_json:Mapped[dict[str,Any]]=mapped_column(JSON); state_hash:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class SimulationEvent(Base):
 __tablename__="simulation_events"; id:Mapped[int]=mapped_column(Integer,primary_key=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); timestamp:Mapped[int]=mapped_column(Integer,index=True); event_type:Mapped[str]=mapped_column(String(80)); entity_ids_json:Mapped[list[str]]=mapped_column(JSON); description:Mapped[str]=mapped_column(Text); evidence_json:Mapped[dict[str,Any]]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class MetricSnapshot(Base):
 __tablename__="metric_snapshots"; id:Mapped[int]=mapped_column(Integer,primary_key=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); timestamp:Mapped[int]=mapped_column(Integer,index=True); metrics_json:Mapped[dict[str,float]]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Anomaly(Base):
 __tablename__="anomalies"; id:Mapped[int]=mapped_column(Integer,primary_key=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); timestamp:Mapped[int]=mapped_column(Integer,index=True); anomaly_type:Mapped[str]=mapped_column(String(80)); severity:Mapped[str]=mapped_column(String(30),index=True); metric:Mapped[str]=mapped_column(String(100)); observed_value:Mapped[float]=mapped_column(Float); expected_value:Mapped[float]=mapped_column(Float); deviation:Mapped[float]=mapped_column(Float); affected_entity_ids_json:Mapped[list[str]]=mapped_column(JSON); evidence_json:Mapped[dict[str,Any]]=mapped_column(JSON); confidence:Mapped[float]=mapped_column(Float); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Prediction(Base):
 __tablename__="predictions"; id:Mapped[int]=mapped_column(Integer,primary_key=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); timestamp:Mapped[int]=mapped_column(Integer,index=True); horizon_minutes:Mapped[int]=mapped_column(Integer); metric:Mapped[str]=mapped_column(String(100)); predicted_value:Mapped[float]=mapped_column(Float); confidence:Mapped[float]=mapped_column(Float); model_name:Mapped[str]=mapped_column(String(100)); feature_evidence_json:Mapped[dict[str,Any]]=mapped_column(JSON); limitations_json:Mapped[list[str]]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Intervention(Base):
 __tablename__="interventions"; id:Mapped[str]=mapped_column(String(80),primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); scenario_id:Mapped[str|None]=mapped_column(ForeignKey("scenarios.id"),index=True); name:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text); parameters_json:Mapped[dict[str,Any]]=mapped_column(JSON); operational_cost:Mapped[float]=mapped_column(Float); safety_score:Mapped[float]=mapped_column(Float); complexity_score:Mapped[float]=mapped_column(Float); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class InterventionRun(Base):
 __tablename__="intervention_runs"; id:Mapped[int]=mapped_column(Integer,primary_key=True); intervention_id:Mapped[str]=mapped_column(ForeignKey("interventions.id")); source_branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id")); result_branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id")); score:Mapped[float]=mapped_column(Float); score_breakdown_json:Mapped[dict[str,Any]]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class Report(Base):
 __tablename__="reports"; id:Mapped[str]=mapped_column(String(80),primary_key=True); world_id:Mapped[str]=mapped_column(ForeignKey("worlds.id"),index=True); branch_id:Mapped[str]=mapped_column(ForeignKey("simulation_branches.id"),index=True); title:Mapped[str]=mapped_column(String(200)); content_markdown:Mapped[str]=mapped_column(Text); content_json:Mapped[dict[str,Any]]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
Index("ix_entity_world_type",Entity.world_id,Entity.entity_type); Index("ix_state_branch_time",SimulationState.branch_id,SimulationState.timestamp); Index("ix_event_branch_time",SimulationEvent.branch_id,SimulationEvent.timestamp); Index("ix_metric_branch_time",MetricSnapshot.branch_id,MetricSnapshot.timestamp); Index("ix_anomaly_branch_severity",Anomaly.branch_id,Anomaly.severity)
